import warnings
from .version import * # Generated by sconsUtils

warnings.warn('Synpipe is deprecated; it will be removed from the Rubin Observatory'
              'Science Pipelines after release 21.0.0', category=FutureWarning)
